Class Book{
    -  title :String
    - pages : List<String> 
    - iterator : ListIterator<String> 
    - currentPage :String
    + Book(String title, List<String> pages) 
    +  getTitle():String
    +  getCurrentPage():String
    +  turnToNextPage():boolean
    
    
    }

interface ReaderServiceInterface {
    +  printToScreen():void
}

interface PublisherServiceInterface{
    +  printToFile():void
}

Class BookPublisher{
    
}

Class BookReader{

}
ReaderServiceInterface --|> Book
PublisherServiceInterface --|> Book

BookPublisher ...|> ReaderServiceInterface:<<implemented>>
BookReader ...|> PublisherServiceInterface:<<implemented>>
